/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Color: typeof import('./src/components/Color/Color.vue')['default']
    ColorCard: typeof import('./src/components/Color/ColorCard.vue')['default']
    Fa6RegularCopy: typeof import('~icons/fa6-regular/copy')['default']
    Font: typeof import('./src/components/Typography/Font.vue')['default']
    FontCard: typeof import('./src/components/Typography/FontCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
