/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Color: typeof import('./src/components/Color/Color.vue')['default']
    ColorCard: typeof import('./src/components/Color/ColorCard.vue')['default']
    Fa6RegularCopy: typeof import('~icons/fa6-regular/copy')['default']
    FontSize: typeof import('./src/components/Typography/FontSize.vue')['default']
    FontSizeCard: typeof import('./src/components/Typography/FontSizeCard.vue')['default']
    FontWeight: typeof import('./src/components/Typography/FontWeight.vue')['default']
    FontWeightCard: typeof import('./src/components/Typography/FontWeightCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacing: typeof import('./src/components/Spacing/Spacing.vue')['default']
    SpacingCard: typeof import('./src/components/Spacing/SpacingCard.vue')['default']
  }
}
