/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Accordion/Accordion.vue')['default']
    Alerts: typeof import('./src/components/Alerts/Alerts.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/Breadcrumb.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Color: typeof import('./src/components/Color/Color.vue')['default']
    ColorCard: typeof import('./src/components/Color/ColorCard.vue')['default']
    Corner: typeof import('./src/components/Corner/Corner.vue')['default']
    CornerCard: typeof import('./src/components/Corner/CornerCard.vue')['default']
    Fa6RegularCopy: typeof import('~icons/fa6-regular/copy')['default']
    Fa6Solid1: typeof import('~icons/fa6-solid/1')['default']
    Fa6SolidAngleRight: typeof import('~icons/fa6-solid/angle-right')['default']
    Fa6SolidAnglesRight: typeof import('~icons/fa6-solid/angles-right')['default']
    Fa6SolidArrowLeftLong: typeof import('~icons/fa6-solid/arrow-left-long')['default']
    Fa6SolidArrowRightLong: typeof import('~icons/fa6-solid/arrow-right-long')['default']
    Fa6SolidCheck: typeof import('~icons/fa6-solid/check')['default']
    Fa6SolidChevronDown: typeof import('~icons/fa6-solid/chevron-down')['default']
    Fa6SolidChevronLeft: typeof import('~icons/fa6-solid/chevron-left')['default']
    Fa6SolidCircleCheck: typeof import('~icons/fa6-solid/circle-check')['default']
    Fa6SolidCircleXmark: typeof import('~icons/fa6-solid/circle-xmark')['default']
    Fa6SolidHouse: typeof import('~icons/fa6-solid/house')['default']
    Fa6SolidStar: typeof import('~icons/fa6-solid/star')['default']
    Fa6SolidXmark: typeof import('~icons/fa6-solid/xmark')['default']
    FontSize: typeof import('./src/components/Typography/FontSize.vue')['default']
    FontSizeCard: typeof import('./src/components/Typography/FontSizeCard.vue')['default']
    FontWeight: typeof import('./src/components/Typography/FontWeight.vue')['default']
    FontWeightCard: typeof import('./src/components/Typography/FontWeightCard.vue')['default']
    IconCard: typeof import('./src/components/Icons/IconCard.vue')['default']
    Icons: typeof import('./src/components/Icons/Icons.vue')['default']
    Pagination: typeof import('./src/components/Pagination/Pagination.vue')['default']
    RangeSlider: typeof import('./src/components/RangeSlider/RangeSlider.vue')['default']
    Ratings: typeof import('./src/components/Ratings/Ratings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Segmented: typeof import('./src/components/Segmented/Segmented.vue')['default']
    Shadow: typeof import('./src/components/Shadow/Shadow.vue')['default']
    ShadowCard: typeof import('./src/components/Shadow/ShadowCard.vue')['default']
    Spacing: typeof import('./src/components/Spacing/Spacing.vue')['default']
    SpacingCard: typeof import('./src/components/Spacing/SpacingCard.vue')['default']
    Stepper: typeof import('./src/components/Stepper/Stepper.vue')['default']
    Tabs: typeof import('./src/components/Tabs/Tabs.vue')['default']
    Timeline: typeof import('./src/components/Timeline/Timeline.vue')['default']
  }
}
